export const products = [
  /*DC comics*/
  {
    name: "Organizador para audifonos de Batman",
    startingPrice: "2",
    category: "Varios",
    tag: "DC comics",
    image: "./images/shop/dc_comics/batman_earphone_holder.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Retenedor de páginas de Batman",
    startingPrice: "2",
    category: "Varios",
    tag: "DC comics",
    image: "./images/shop/dc_comics/batman_page_holder.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Soporte para Alexa de Mujer Maravilla",
    startingPrice: "25",
    category: "Adornos",
    subcategory: "DC comics",
    tag: "DC comics",
    image: "./images/shop/dc_comics/echo_ww.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Lámpara de Pared de Batman",
    startingPrice: "40",
    category: "Adornos",
    subcategory: "DC comics",
    tag: "DC comics",
    image: "./images/shop/dc_comics/lampara_pared_batman.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Llavero Batman",
    startingPrice: "1",
    category: "Llaveros",
    subcategory: "DC comics",
    tag: "DC comics",
    image: "./images/shop/dc_comics/llavero.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Llavero Superman",
    startingPrice: "1",
    category: "Llaveros",
    subcategory: "DC comics",
    tag: "DC comics",
    image: "./images/shop/dc_comics/llavero_Superman.jpg",
    isNew: false,
    isSale: false,
  },
/* Fortnite*/
  {
    name: "Figura Raven",
    startingPrice: "5", //5-20$
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Fortnite",
    tag: "Fortnite",
    image: "./images/shop/Fortnite/figura.jpeg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura cofre de Fortnite",
    startingPrice: "8",//8-20$
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Fortnite",
    tag: "Fortnite",
    image: "./images/shop/Fortnite/cofre.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "No Molestar",
    startingPrice: "10",
    category: "Adornos",
    subcategory: "Fortnite",
    tag: "Fortnite",
    image: "./images/shop/Fortnite/letrero.jpg",
    isNew: false,
    isSale: false,
  },
  // Game of Thrones
  {
    name: "Calendario de escritorio",
    startingPrice: "35",
    category: "Adornos",
    subcategory: "Game of Thrones",
    tag: "Game of Thrones",
    image: "./images/shop/GOT/desk_calendar.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Huevo de Dragón",
    startingPrice: "8", //8-22
    maxPrice: "22",
    category: "Figuras",
    subcategory: "Game of Thrones",
    tag: "Game of Thrones",
    image: "./images/shop/GOT/egg.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Separador de Hojas de la casa Stark",
    startingPrice: "3",
    category: "separadores",
    subcategory: "Game of Thrones",
    tag: "Game of Thrones",
    image: "./images/shop/GOT/GOT1.JPG",
    isNew: false,
    isSale: false,
  },
  {
    name: "Árbol de Winterfell para joyería",
    startingPrice: "8",
    category: "Adornos",
    subcategory: "Game of Thrones",
    tag: "Game of Thrones",
    image: "./images/shop/GOT/joyas.jpg",
    isNew: false,
    isSale: false,
  },
  //Harry Potter
  {
    name: "Bombillo Harry Potter",
    startingPrice: "1",
    category: "Varios",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/bombillo.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Separadores de las Casas de Harry Potter",
    startingPrice: "2",
    category: "separadores",
    subcategory: "Harry Potter",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/bookmark_casas.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Reliquias de la Muerte",
    startingPrice: "1",
    category: "separadores",
    subcategory: "Harry Potter",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/Bookmark_reliquiasdelamuerte.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Cake Topper Always",
    startingPrice: "3",
    category: "Varios",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/cake_topper.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura de Harry Potter",
    startingPrice: "10", //10-25
    maxPrice: "25",
    category: "Figuras",
    subcategory: "Harry Potter",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/figura_hp.png",
    isNew: false,
    isSale: false,
  },
  {
    name: "Llavero de Harry Potter",
    startingPrice: "2",
    category: "Llaveros",
    subcategory: "Harry Potter",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/llavero.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Llavero de la estación 9 3/4",
    startingPrice: "2",
    category: "Llaveros",
    subcategory: "Harry Potter",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/llavero_hp2.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Llavero de las reliquias de la muerte",
    startingPrice: "1",
    category: "Llaveros",
    subcategory: "Harry Potter",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/llavero2.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Posavasos de casas de Harry Potter",
    startingPrice: "5",
    category: "Varios",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/posa_vasos.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Soporte para celular de Harry Potter",
    startingPrice: "12",
    category: "Adornos",
    subcategory: "Harry Potter",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/soporte_celular.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Candelabro Slytherin",
    startingPrice: "20",
    category: "Adornos",
    subcategory: "Harry Potter",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/stand_slytherin.png",
    isNew: false,
    isSale: false,
  },
  {
    name: "Varita mágica Harry Potter",
    startingPrice: "25",
    category: "Varios",
    subcategory: "Harry Potter",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/varita_elder.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Candelabro espina dorsal de Harry Potter",
    startingPrice: "15",
    category: "Adornos",
    subcategory: "Harry Potter",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/vela_espina.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Soporte para Varita de Harry Potter",
    startingPrice: "20",
    category: "Adornos",
    subcategory: "Harry Potter",
    tag: "Harry Potter",
    image: "./images/shop/Harry Potter/wand_holder.jpg",
    isNew: false,
    isSale: false,
  },
  //League of Legends
  {
    name: "Figura Pengu de Teamfight Tactics",
    startingPrice: "8", //8-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "League of Legends",
    tag: "League of Legends",
    image: "./images/shop/League of Legends/dududunga.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura Pengu Tier 3 de Teamfight Tactics",
    startingPrice: "8", //8-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "League of Legends",
    tag: "League of Legends",
    image: "./images/shop/League of Legends/dududunga2.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura Jhin Luna sangrienta",
    startingPrice: "8", //8-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "League of Legends",
    tag: "League of Legends",
    image: "./images/shop/League of Legends/jhin_bloodmon.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura Poro de League of Legends",
    startingPrice: "8", //8-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "League of Legends",
    tag: "League of Legends",
    image: "./images/shop/League of Legends/poro.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura Veigar",
    startingPrice: "8", //8-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "League of Legends",
    tag: "League of Legends",
    image: "./images/shop/League of Legends/veigar.jpg",
    isNew: false,
    isSale: false,
  },
  //Mario Bros
  {
    name: "Bombillo de Estrella de Mario Bros",
    startingPrice: "1", 
    category: "Varios",
    //subcategory: "Mario Bros",
    tag: "Mario Bros",
    image: "./images/shop/mario_Bros/bombillo.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura de Planta Piraña",
    startingPrice: "8", //8-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Mario Bros",
    tag: "Mario Bros",
    image: "./images/shop/mario_Bros/flower.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Porta Lapices de Mario Bros",
    startingPrice: "15", 
    category: "Adornos",
    subcategory: "Mario Bros",
    tag: "Mario Bros",
    image: "./images/shop/mario_Bros/pencil.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Maceta de Mario Bros ",
    startingPrice: "10", //10-20
    maxPrice: "20",
    category: "Macetas",
    subcategory: "Mario Bros",
    tag: "Mario Bros",
    image: "./images/shop/mario_Bros/pot.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Maceta de árbol ",
    startingPrice: "6", //6-12
    maxPrice: "12",
    category: "Macetas",
    subcategory: "Mario Bros",
    tag: "Mario Bros",
    image: "./images/shop/mario_Bros/pot_tree.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Maceta de tubo de Mario Bros ",
    startingPrice: "6", //6-12
    maxPrice: "12",
    category: "Macetas",
    subcategory: "Mario Bros",
    tag: "Mario Bros",
    image: "./images/shop/mario_Bros/pot2.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Estrella de Mario Bros ",
    startingPrice: "1", 
    category: "Varios",
    //subcategory: "Mario Bros",
    tag: "Mario Bros",
    image: "./images/shop/mario_Bros/star_ornament.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Organizador para nintendo switch",
    startingPrice: "20", 
    category: "Adornos",
    subcategory: "Mario Bros",
    tag: "Mario Bros",
    image: "./images/shop/mario_Bros/switch.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Hongo de Mario Bros ",
    startingPrice: "1", //10-20
    category: "Varios",
    tag: "Mario Bros",
    image: "./images/shop/mario_Bros/star_ornament.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Organizador para nintendo switch de roca",
    startingPrice: "20", 
    category: "Adornos",
    subcategory: "Mario Bros",
    tag: "Mario Bros",
    image: "./images/shop/mario_Bros/switch2.jpg",
    isNew: false,
    isSale: false,
  },
  //Marvel
  {
    name: "Figura Pantera Negra ",
    startingPrice: "8", //10-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Marvel",
    tag: "Marvel",
    image: "./images/shop/marvel/black_panther.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura Groot bailarin ",
    startingPrice: "10", //10-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Marvel",
    tag: "Marvel",
    image: "./images/shop/marvel/dancing groot.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura deadpool ",
    startingPrice: "8", //8-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Marvel",
    tag: "Marvel",
    image: "./images/shop/marvel/deadpool.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura baby groot ",
    startingPrice: "8", //8-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Marvel",
    tag: "Marvel",
    image: "./images/shop/marvel/groot_baby.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura spiderman homecoming",
    startingPrice: "8", //8-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Marvel",
    tag: "Marvel",
    image: "./images/shop/marvel/spiderman.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura Venom y Peter Parker ",
    startingPrice: "10", //10-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Marvel",
    tag: "Marvel",
    image: "./images/shop/marvel/venom_peter.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Soporte para control con Hulk",
    startingPrice: "15", 
    category: "Adornos",
    subcategory: "Marvel",
    tag: "Marvel",
    image: "./images/shop/marvel/soporte_control.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Esfero de Thor",
    startingPrice: "20", 
    category: "Adornos",
    subcategory: "Marvel",
    tag: "Marvel",
    image: "./images/shop/marvel/thor_esfero.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Llavero de Mjolnir de Thor",
    startingPrice: "2", 
    category: "Llaveros",
    subcategory: "Marvel",
    tag: "Marvel",
    image: "./images/shop/marvel/llavero_thor.png",
    isNew: false,
    isSale: false,
  },
  {
    name: "Separador de Hojas Capitán América",
    startingPrice: "1", 
    category: "separadores",
    subcategory: "Marvel",
    tag: "Marvel",
    image: "./images/shop/marvel/bookmark_capamerica.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Separador de Hojas Spiderman",
    startingPrice: "1", 
    category: "separadores",
    subcategory: "Marvel",
    tag: "Marvel",
    image: "./images/shop/marvel/bookmark_spiderman.jpg",
    isNew: false,
    isSale: false,
  },
  //Minecraft
  {
    name: "Dragon Minecraft",
    startingPrice: "12", //10-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Minecraft",
    tag: "Minecraft",
    image: "./images/shop/minecraft/dragon.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Llaveros Minecraft",
    startingPrice: "1", 
    category: "Llaveros",
    subcategory: "Minecraft",
    tag: "Minecraft",
    image: "./images/shop/minecraft/llaveros.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura de Minecraft",
    startingPrice: "7", //7-14
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Minecraft",
    tag: "Minecraft",
    image: "./images/shop/minecraft/minecraft.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Letrero Minecraft",
    startingPrice: "25",
    category: "Adornos",
    subcategory: "Minecraft",
    tag: "Minecraft",
    image: "./images/shop/minecraft/logo_minecraft.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Halloween Minecraft",
    startingPrice: "12", //12-20
    maxPrice: "20",
    category: "Adornos",
    subcategory: "Minecraft",
    tag: "Minecraft",
    image: "./images/shop/minecraft/minecraft_halloween.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Organizador de juegos de switch de Minecraft",
    startingPrice: "25",
    category: "Adornos",
    subcategory: "Minecraft",
    tag: "Minecraft",
    image: "./images/shop/minecraft/switch.jpg",
    isNew: false,
    isSale: false,
  },
  //Naruto
  {
    name: "Símbolo de Aldea de la Hoja",
    startingPrice: "10",
    category: "Adornos",
    subcategory: "Naruto",
    tag: "Naruto",
    image: "./images/shop/naruto/naruto_symbol.jpg",
    isNew: false,
    isSale: false,
  },
  {
    name: "Figura de Pikachu como Kakashi",
    startingPrice: "10", //10-20
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Naruto",
    tag: "Naruto",
    image: "./images/shop/naruto/pika.jpg",
    isNew: false,
    isSale: false,
  },
  //Pokemon
  {
    name: "Maceta Bulbasaur",
    startingPrice: "6",//6-10
    maxPrice: "10",
    category: "Macetas",
    subcategory: "Pokemon",
    tag: "Pokemon",
    image: "./images/shop/Pokemon/pot_bulbasaur.jpg",
    isNew: false,
  },
  {
    name: "Maceta Pokeball",
    startingPrice: "6",//6-10
    maxPrice: "10",
    category: "Macetas",
    subcategory: "Pokemon",
    tag: "Pokemon",
    image: "./images/shop/Pokemon/pokeball_pot.jpg",
    isNew: false,
  },
  {
    name: "Maceta Oddish",
    startingPrice: "6",//6-10
    maxPrice: "10",
    category: "Macetas",
    subcategory: "Pokemon",
    tag: "Pokemon",
    image: "./images/shop/Pokemon/oddish_pot3.jpg",
    isNew: false,
  },
  {
    name: "Llavero Pokemon Go",
    startingPrice: "2",//6-10
    category: "Llaveros",
    subcategory: "Pokemon",
    tag: "Pokemon",
    image: "./images/shop/Pokemon/llavero2.jpg",
    isNew: false,
  },
  {
    name: "Llavero Cubone",
    startingPrice: "2",
    category: "Llaveros",
    subcategory: "Pokemon",
    tag: "Pokemon",
    image: "./images/shop/Pokemon/cubone_llavero.jpg",
    isNew: false,
  },
  {
    name: "Llavero Pokeball",
    startingPrice: "2",
    category: "Llaveros",
    subcategory: "Pokemon",
    tag: "Pokemon",
    image: "./images/shop/Pokemon/llavero_pokeball.jpg",
    isNew: false,
  },
  {
    name: "Figura Gengar",
    startingPrice: "8",//8-12
    maxPrice: "12",
    category: "Figuras",
    subcategory: "Pokemon",
    tag: "Pokemon",
    image: "./images/shop/Pokemon/gengar.jpg",
    isNew: false,
  },
  {
    name: "Figura abra",
    startingPrice: "8",//8-12
    maxPrice: "12",
    category: "Figuras",
    subcategory: "Pokemon",
    tag: "Pokemon",
    image: "./images/shop/Pokemon/abra.jpg",
    isNew: false,
  },
  {
    name: "Organizar de juegos de Nintendo Switch con forma de Pokeball",
    startingPrice: "8",//8-12
    maxPrice: "12",
    category: "Adornos",
    subcategory: "Pokemon",
    tag: "Pokemon",
    image: "./images/shop/Pokemon/pokeball_switch.jpg",
    isNew: false,
  },
  //Star Wars
  {
    name: "Separador de hojas de Storm Trooper",
    startingPrice: "2",
    category: "separadores",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/Bookmark_stormtrooper.jpg",
    isNew: false,
  },
  {
    name: "Buda Darth Vader",
    startingPrice: "8",//8-12
    maxPrice: "15",
    category: "Figuras",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/buddah.jpg",
    isNew: false,
  },
  {
    name: "Anillo de la Rebelión",
    startingPrice: "7",
    category: "Figuras",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/rebel_ring.jpg",
    isNew: false,
  },
  {
    name: "Soporte para bolígrafo de Darth Vader",
    startingPrice: "10",
    category: "Adornos",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/darth_pen_holder.jpg",
    isNew: false,
  },
  {
    name: "Soporte para Alexa o Google Home de R2D2 ",
    startingPrice: "20",
    category: "Adornos",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/google_home.jpg",
    isNew: false,
  },
  {
    name: "Soporte para celular de Star Wars",
    startingPrice: "7",
    category: "Adornos",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/soporte.jpg",
    isNew: false,
  },
  {
    name: "Maceta de Darth Vader",
    startingPrice: "6", //6-10
    maxPrice: "10",
    category: "Macetas",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/pot darth vader.jpg",
    isNew: false,
  },
  {
    name: "Llavero de los dados de Han Solo",
    startingPrice: "5",
    category: "Llaveros",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/han_solo_dice.jpg",
    isNew: false,
  },
  {
    name: "Llavero de Star Wars",
    startingPrice: "1",
    category: "Llaveros",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/llavero.jpg",
    isNew: false,
  },
  {
    name: "Llavero del Halcón Milenario",
    startingPrice: "3",
    category: "Llaveros",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/llavero_starwars.jpg",
    isNew: false,
  },
  {
    name: "Llavero de la Estrella de la Muerte",
    startingPrice: "3",
    category: "Llaveros",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/llavero_starwars2.jpg",
    isNew: false,
  },
  {
    name: "Llavero de Storm Trooper",
    startingPrice: "2",
    category: "Llaveros",
    subcategory: "Star Wars",
    tag: "Star Wars",
    image: "./images/shop/star_wars/llavero2.jpg",
    isNew: false,
  },
  //Varios
  {
    name: "Maceta de Among US con autoriego",
    startingPrice: "10",
    maxPrice: "20",
    category: "Macetas",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/among_us_pot.jpg",
    isNew: false,
  },
  {
    name: "Figura de Avatar",
    startingPrice: "15", 
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/avatar.jpg",
    isNew: false,
  },
  {
    name: "Figura de Blanka de Street Fighter",
    startingPrice: "8", //8-12 
    maxPrice: "12",
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/blanka_sf.jpg",
    isNew: false,
  },
  {
    name: "Separador de Hojas de la Torre Eiffel",
    startingPrice: "1", 
    category: "separadores",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/bookmark_eiffel.jpg",
    isNew: false,
  },
  {
    name: "Separador de Hojas de una torre de reloj",
    startingPrice: "1", 
    category: "separadores",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/bookmark_tower.jpg",
    isNew: false,
  },
  {
    name: "Bombillo del hombre de gengibre ",
    startingPrice: "3", 
    category: "Varios",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/cookie_shrek.jpg",
    isNew: false,
  },
  {
    name: "Cobertor de cámara web",
    startingPrice: "1", 
    category: "Varios",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/cubre_camara2.png",
    isNew: false,
  },
  {
    name: "Cobertor de cámara web Apple",
    startingPrice: "3", 
    category: "Varios",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/cubre_camera.jpg",
    isNew: false,
  },
  {
    name: "Cobertor de drenaje",
    startingPrice: "3", 
    category: "Varios",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/drainer.jpg",
    isNew: false,
  },
  {
    name: "Figura de Puro Hueso de Billy y Mandy",
    startingPrice: "10", //10-25 
    maxPrice: "25",
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/figura_grim.png",
    isNew: false,
  },
  {
    name: "Raze de Valorant en Among Us",
    startingPrice: "10", //10-25 
    maxPrice: "25",
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/figura_razeau.jpg",
    isNew: false,
  },
  {
    name: "Figura de Alphonse Elric",
    startingPrice: "10", //10-25 
    maxPrice: "25",
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/fma.jpg",
    isNew: false,
  },
  {
    name: "Figura de Fry de Futurama",
    startingPrice: "10", //10-25 
    maxPrice: "25",
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/fry.jpg",
    isNew: false,
  },
  {
    name: "Soporte de anteojos de Dragón",
    startingPrice: "10", 
    category: "Adornos",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/glasses_holder.jpg",
    isNew: false,
  },
  {
    name: "Figura de Fantasmas de Halloween",
    startingPrice: "10", 
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/halloween.jpg",
    isNew: false,
  },
  {
    name: "Figura del gigante de acero",
    startingPrice: "10", //10-25
    maxPrice: "25", 
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/iron_giant.jpg",
    isNew: false,
  },
  {
    name: "Figura de Shinobu de Kimetsu no Yaiba",
    startingPrice: "15", //15-25 
    maxPrice: "25",
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/kimetsu_1.jpg",
    isNew: false,
  },
  {
    name: "Llavero de Valorant Breach",
    startingPrice: "3", 
    category: "Llaveros",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/llavero_breach.jpg",
    isNew: false,
  },
  {
    name: "Llavero de Valorant Phoenix",
    startingPrice: "3", 
    category: "Llaveros",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/llavero_phoenix.jpg",
    isNew: false,
  },
  {
    name: "Llavero de L de Death Note",
    startingPrice: "2", 
    category: "Llaveros",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/llavero_L.jpg",
    isNew: false,
  },
  {
    name: "Figura de One Punch Man",
    startingPrice: "10", //10-20 
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/one_punch2.jpg",
    isNew: false,
  },
  {
    name: "Soporte para celular de Montacargas",
    startingPrice: "27", 
    category: "Adornos",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/montacargas_soport.jpg",
    isNew: false,
  },
  {
    name: "Maceta de Buho",
    startingPrice: "6", //6-10 
    maxPrice: "10",
    category: "Macetas",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/pot_buho.jpg",
    isNew: false,
  },
  {
    name: "Maceta con forma de Pirámide",
    startingPrice: "6", //6-10 
    maxPrice: "10",
    category: "Macetas",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/pot_pyramid.jpg",
    isNew: false,
  },
  {
    name: "Figura de Morty",
    startingPrice: "10", //10-25 
    maxPrice: "25",
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/ramorty_morty.jpg",
    isNew: false,
  },
  {
    name: "Figura de Rick",
    startingPrice: "10", //10-25 
    maxPrice: "25",
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/ramorty_rick.jpg",
    isNew: false,
  },
  {
    name: "Figura de Rick bebiendo",
    startingPrice: "10", //10-25 
    maxPrice: "25",
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/ramorty_rick2.jpg",
    isNew: false,
  },
  {
    name: "Butter Robot como soporte de bolígrafo",
    startingPrice: "7", 
    category: "Adornos",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/ramorty_robot.jpg",
    isNew: false,
  },
  {
    name: "Bombillo de Space Invaders",
    startingPrice: "1", 
    category: "Varios",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/space_invaders.jpg",
    isNew: false,
  },
  {
    name: "Soportes personalizados para Celular",
    startingPrice: "9", 
    category: "Adornos",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/stand_ldu.jpg",
    isNew: false,
  },
  {
    name: "Soportes personalizados para PS4/XBOX",
    startingPrice: "6", 
    category: "Varios",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/stand_ps4.jpg",
    isNew: false,
  },
  {
    name: "Figura de Unicornio",
    startingPrice: "8", //8-20 
    maxPrice: "20",
    category: "Figuras",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/unicornio.jpg",
    isNew: false,
  },
  {
    name: "Llavero de Zelda",
    startingPrice: "2", 
    category: "Llaveros",
    subcategory: "Otros",
    tag: "Otros",
    image: "./images/shop/Varios/zelda_llavero.jpg",
    isNew: false,
  },
]